### ISSUE TITLE
Confirm important Story fields for mobile app end users

### ISSUE THREAD

**Issue by nathanbaleeta** [nathanbaleeta/ureport-mobile#13]
The U-Report public API endpoint for the stories exposes the data fields below for consuming. Could you verify with the U-Report team which fields would be priority for the mobile app.

 
```
{
		"id": Integer,
		"title": "String.",
		"featured": Bolean,
		"summary": "String",
		"video_id": Integer,
		"audio_link": String,
		"tags": " String ",
		"org": Integer,
		"images": ["String"],
		"category": {
			"image_url": "String",
			"name": "String"
		},
		"created_on": "datetime"
       }

```

**Comment by alee8599** [comment]
Yes, I can send an email to Chris asking about this.

**Comment by alee8599** [comment]
@nathanbaleeta I'm sure you saw the email as well but I will post the information here as well: 

You can take your cues from the website listing for stories: https://ureport.in/stories/

I also thought the suggestion of ordering/filtering by tags is a good one, although I don’t think that today many programmes are likely to make extensive use of the tags because they don’t show on the website.

-----

The stories are unique to each U-Report programme, ie U-Report Nigeria is separate from U-Report Myanmar. This is quite important because the programme manager and the steering committee has complete control over which stories appear for their programme. So we should keep the stories segmented by programme.

It would be interesting to suggest to COs that they could re-post stories from the Global platform, but I think this could be done manually without having to add a feature.
